apiVersion: v1
kind: Service
metadata:
  name: hello-eks
  namespace: hello
  labels:
    app: hello-eks
  annotations:
    # Network Load Balancer, internet-facing -> gives a browsable public URL
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  selector:
    app: hello-eks
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
